import { Ban, Check, ClipboardPlus, Clock, ListOrdered } from "lucide-react";
import { Truck } from "lucide-react";
import { RotateCcw } from "lucide-react";
import { Users } from "lucide-react";
import { Package, ClipboardEdit, BarChart2 } from "lucide-react";
export const pages = [
  {
    name: "جميع الطلبات",
    link: "/all-orders",
    icon: <ListOrdered />,
  },
  {
    name: "إدارة المخزون",
    link: "/stock-management",
    icon: <Package />,
    role: "accountant",
  },
  {
    name: "معالجة المرتجعات",
    link: "/returns-processing",
    icon: <ClipboardEdit />,
    role: ["accountant", "stock_manager"],
  },
  {
    name: "التقارير والإحصائيات",
    link: "/reports",
    icon: <BarChart2 />,
    role: "owner",
  },
  {
    name: "الطلبات الجديدة",
    link: "/new-orders",
    icon: <ClipboardPlus />,
  },
  {
    name: "الطلبات المؤجلة",
    link: "/delayed-orders",
    icon: <Clock />,
  },
  {
    name: "الطلبات الملغاة",
    link: "/cancelled-orders",
    icon: <Ban />,
  },
  {
    name: "الطلبات المؤكدة",
    link: "/confirmed-orders",
    icon: <Check />,
  },
  {
    name: "الطلبات المشحونة",
    link: "/shipped-orders",
    icon: <Truck />,
  },
  {
    name: "الطلبات المرتجعة",
    link: "/returned-orders",
    icon: <RotateCcw />,
  },
  {
    name: "الطلبات المستلمة",
    link: "/completed-orders",
    icon: <Check />,
  },
  {
    name: "بيانات العملاء",
    link: "/users-data",
    icon: <Users />,
  },
];
// Customers data based on the API schema
export const customers = [
  {
    id: 1,
    fullName: "أحمد محمد",
    phone: "0501234567",
    location: "الرياض، حي النخيل",
    customerState: 1,
    subSystemId: 1,
    subSystem: {
      id: 1,
      name: "النظام الفرعي الأول",
      domain: "subsystem1.domain.com",
      apI_KEY: "api_key_1",
      subSystemState: 1,
      createdAt: "2023-01-01T12:00:00Z",
    },
  },
  {
    id: 2,
    fullName: "سارة علي",
    phone: "0567890123",
    location: "جدة، حي الروضة",
    customerState: 2,
    subSystemId: 1,
    subSystem: {
      id: 1,
      name: "النظام الفرعي الأول",
      domain: "subsystem1.domain.com",
      apI_KEY: "api_key_1",
      subSystemState: 1,
      createdAt: "2023-01-01T12:00:00Z",
    },
  },
  {
    id: 3,
    fullName: "محمد عبدالله",
    phone: "0512345678",
    location: "الدمام، حي الشاطئ",
    customerState: 0,
    subSystemId: 1,
    subSystem: {
      id: 1,
      name: "النظام الفرعي الأول",
      domain: "subsystem1.domain.com",
      apI_KEY: "api_key_1",
      subSystemState: 1,
      createdAt: "2023-01-01T12:00:00Z",
    },
  },
  {
    id: 4,
    fullName: "فهد سعيد",
    phone: "0523456789",
    location: "الرياض، حي الورود",
    customerState: 0,
    subSystemId: 2,
    subSystem: {
      id: 2,
      name: "النظام الفرعي الثاني",
      domain: "subsystem2.domain.com",
      apI_KEY: "api_key_2",
      subSystemState: 1,
      createdAt: "2023-02-01T12:00:00Z",
    },
  },
  {
    id: 5,
    fullName: "نورة محمد",
    phone: "0534567890",
    location: "جدة، حي السلامة",
    customerState: 0,
    subSystemId: 2,
    subSystem: {
      id: 2,
      name: "النظام الفرعي الثاني",
      domain: "subsystem2.domain.com",
      apI_KEY: "api_key_2",
      subSystemState: 1,
      createdAt: "2023-02-01T12:00:00Z",
    },
  },
  {
    id: 6,
    fullName: "خالد عبدالرحمن",
    phone: "0545678901",
    location: "الرياض، حي الملز",
    customerState: 0,
    subSystemId: 1,
    subSystem: {
      id: 1,
      name: "النظام الفرعي الأول",
      domain: "subsystem1.domain.com",
      apI_KEY: "api_key_1",
      subSystemState: 1,
      createdAt: "2023-01-01T12:00:00Z",
    },
  },
  {
    id: 7,
    fullName: "عبير أحمد",
    phone: "0556789012",
    location: "مكة، حي العزيزية",
    customerState: 1,
    subSystemId: 2,
    subSystem: {
      id: 2,
      name: "النظام الفرعي الثاني",
      domain: "subsystem2.domain.com",
      apI_KEY: "api_key_2",
      subSystemState: 1,
      createdAt: "2023-02-01T12:00:00Z",
    },
  },
  {
    id: 8,
    fullName: "سعود فيصل",
    phone: "0567890123",
    location: "جدة، حي الصفا",
    customerState: 1,
    subSystemId: 1,
    subSystem: {
      id: 1,
      name: "النظام الفرعي الأول",
      domain: "subsystem1.domain.com",
      apI_KEY: "api_key_1",
      subSystemState: 1,
      createdAt: "2023-01-01T12:00:00Z",
    },
  },
];

// Orders data based on the API schema
export const newOrders = [
  {
    id: 1,
    orderState: 0, // جديد
    orderDate: "2023-08-25T10:30:00Z",
    deliveryDate: null,
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 100,
    shippingCost: 15,
    shippingAddress: "الرياض، حي النخيل",
    trackingCode: null,
    customerId: 1,
    shippingProviderId: 1,
    imageUrl: "images/product-1.jpeg",
  },
  {
    id: 2,
    orderState: 0, // جديد
    orderDate: "2023-08-25T14:20:00Z",
    deliveryDate: null,
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 300,
    shippingCost: 15,
    shippingAddress: "جدة، حي الروضة",
    trackingCode: null,
    customerId: 2,
    shippingProviderId: 1,
    imageUrl: "images/product-2.jpeg",
  },
  {
    id: 3,
    orderState: 0, // جديد
    orderDate: "2023-08-24T09:15:00Z",
    deliveryDate: null,
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 1200,
    shippingCost: 0,
    shippingAddress: "الدمام، حي الشاطئ",
    trackingCode: null,
    customerId: 3,
    shippingProviderId: 2,
    imageUrl: "images/product-3.jpeg",
  },
  {
    id: 4,
    orderState: 2, // مؤجل
    orderDate: "2023-08-23T11:45:00Z",
    deliveryDate: null,
    delayedUntil: "2023-09-05T00:00:00Z",
    delayedReason: "نفاد المخزون، بانتظار شحنة جديدة",
    totalPrice: 2500,
    shippingCost: 25,
    shippingAddress: "الرياض، حي الورود",
    trackingCode: null,
    customerId: 4,
    shippingProviderId: 1,
    imageUrl: "images/product-4.jpeg",
  },
  {
    id: 5,
    orderState: 2, // مؤجل
    orderDate: "2023-08-22T16:30:00Z",
    deliveryDate: null,
    delayedUntil: "2023-09-03T00:00:00Z",
    delayedReason: "تأخير في الشحن",
    totalPrice: 95,
    shippingCost: 15,
    shippingAddress: "جدة، حي السلامة",
    trackingCode: null,
    customerId: 5,
    shippingProviderId: 2,
    imageUrl: "images/product-5.jpeg",
  },
  {
    id: 6,
    orderState: 3, // ملغي
    orderDate: "2023-08-21T13:20:00Z",
    deliveryDate: null,
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 1500,
    shippingCost: 20,
    shippingAddress: "الرياض، حي الملز",
    trackingCode: null,
    customerId: 6,
    shippingProviderId: 1,
    imageUrl: "images/product-1.jpeg",
  },
  {
    id: 7,
    orderState: 3, // ملغي
    orderDate: "2023-08-20T10:10:00Z",
    deliveryDate: null,
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 800,
    shippingCost: 15,
    shippingAddress: "مكة، حي العزيزية",
    trackingCode: null,
    customerId: 7,
    shippingProviderId: 2,
    imageUrl: "images/product-2.jpeg",
  },
  {
    id: 8,
    orderState: 1, // مؤكد
    orderDate: "2023-08-19T15:40:00Z",
    deliveryDate: "2023-08-25T00:00:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 400,
    shippingCost: 15,
    shippingAddress: "جدة، حي الصفا",
    trackingCode: null,
    customerId: 8,
    shippingProviderId: 1,
    imageUrl: "images/product-3.jpeg",
  },
  {
    id: 9,
    orderState: 1, // مؤكد
    orderDate: "2023-08-18T12:30:00Z",
    deliveryDate: "2023-08-24T00:00:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 240,
    shippingCost: 15,
    shippingAddress: "الرياض، حي الياسمين",
    trackingCode: null,
    customerId: 1,
    shippingProviderId: 2,
    imageUrl: "images/product-4.jpeg",
  },
  {
    id: 10,
    orderState: 1, // مؤكد
    orderDate: "2023-08-17T09:25:00Z",
    deliveryDate: "2023-08-23T00:00:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 75,
    shippingCost: 15,
    shippingAddress: "الدمام، حي الفيصلية",
    trackingCode: null,
    customerId: 3,
    shippingProviderId: 1,
    imageUrl: "images/product-5.jpeg",
  },
  {
    id: 11,
    orderState: 4, // مشحون
    orderDate: "2023-08-16T11:15:00Z",
    deliveryDate: "2023-08-22T00:00:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 255,
    shippingCost: 15,
    shippingAddress: "الرياض، حي الربيع",
    trackingCode: "SHP12345678",
    customerId: 2,
    shippingProviderId: 1,
    imageUrl: "images/product-1.jpeg",
  },
  {
    id: 12,
    orderState: 4, // مشحون
    orderDate: "2023-08-15T14:50:00Z",
    deliveryDate: "2023-08-21T00:00:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 750,
    shippingCost: 20,
    shippingAddress: "جدة، حي المروة",
    trackingCode: "SHP23456789",
    customerId: 4,
    shippingProviderId: 2,
    imageUrl: "images/product-2.jpeg",
  },
  {
    id: 13,
    orderState: 5, // مستلم
    orderDate: "2023-08-14T10:30:00Z",
    deliveryDate: "2023-08-20T13:45:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 350,
    shippingCost: 15,
    shippingAddress: "الرياض، حي الخليج",
    trackingCode: "SHP34567890",
    customerId: 5,
    shippingProviderId: 1,
    imageUrl: "images/product-3.jpeg",
  },
  {
    id: 14,
    orderState: 5, // مستلم
    orderDate: "2023-08-13T09:20:00Z",
    deliveryDate: "2023-08-19T15:30:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 120,
    shippingCost: 15,
    shippingAddress: "مكة، حي النسيم",
    trackingCode: "SHP45678901",
    customerId: 6,
    shippingProviderId: 2,
    imageUrl: "images/product-4.jpeg",
  },
  {
    id: 15,
    orderState: 6, // مرتجع
    orderDate: "2023-08-12T13:10:00Z",
    deliveryDate: "2023-08-18T14:25:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 220,
    shippingCost: 15,
    shippingAddress: "الرياض، حي العليا",
    trackingCode: "SHP56789012",
    customerId: 7,
    shippingProviderId: 1,
    imageUrl: "images/product-5.jpeg",
  },
  {
    id: 16,
    orderState: 6, // مرتجع
    orderDate: "2023-08-11T11:40:00Z",
    deliveryDate: "2023-08-17T12:35:00Z",
    delayedUntil: null,
    delayedReason: null,
    totalPrice: 650,
    shippingCost: 15,
    shippingAddress: "جدة، حي البوادي",
    trackingCode: "SHP67890123",
    customerId: 8,
    shippingProviderId: 2,
    imageUrl: "images/product-1.jpeg",
  },
];
