import { Ban, Check, ClipboardPlus, Clock, ListOrdered } from "lucide-react";
import { Truck } from "lucide-react";
import { RotateCcw } from "lucide-react";
import { Users } from "lucide-react";
export const pages = [
  {
    name: "جميع الطلبات",
    link: "/all-orders",
    icon: <ListOrdered />,
  },
  {
    name: "الطلبات الجديدة",
    link: "/new-orders",
    icon: <ClipboardPlus />,
  },
  {
    name: "الطلبات المؤجلة",
    link: "/delayed-orders",
    icon: <Clock />,
  },
  {
    name: "الطلبات الملغاة",
    link: "/cancelled-orders",
    icon: <Ban />,
  },
  {
    name: "الطلبات المؤكدة",
    link: "/confirmed-orders",
    icon: <Check />,
  },
  {
    name: "الطلبات المشحونة",
    link: "/shipped-orders",
    icon: <Truck />,
  },
  {
    name: "الطلبات المرتجعة",
    link: "/returned-orders",
    icon: <RotateCcw />,
  },
  {
    name: "الطلبات المستلمة",
    link: "/completed-orders",
    icon: <Check />,
  },
  {
    name: "بيانات العملاء",
    link: "/users-data",
    icon: <Users />,
  },
];
export const newOrders = [
  {
    id: 1,
    product: "سماعات لاسلكية",
    price: 100,
    quantity: 1,
    total: 100,
    status: "تحت المراجعة",
    date: "2023-08-25",
    customer: "أحمد محمد",
    image: "../../images/product-1.jpeg",
    phone: "0501234567",
    address: "الرياض، حي النخيل",
  },
  {
    id: 2,
    product: "ساعة ذكية",
    price: 150,
    quantity: 2,
    total: 300,
    status: "تحت المراجعة",
    date: "2023-08-25",
    customer: "سارة علي",
    image: "../../images/product-2.jpeg",
    phone: "0567890123",
    address: "جدة، حي الروضة",
  },
  {
    id: 3,
    product: "جوال ذكي",
    price: 1200,
    quantity: 1,
    total: 1200,
    status: "تحت المراجعة",
    date: "2023-08-24",
    customer: "محمد عبدالله",
    image: "../../images/product-3.jpeg",
    phone: "0512345678",
    address: "الدمام، حي الشاطئ",
  },

  {
    id: 4,
    product: "لابتوب محمول",
    price: 2500,
    quantity: 1,
    total: 2500,
    status: "مؤجل",
    date: "2023-08-23",
    customer: "فهد سعيد",
    image: "../../images/product-4.jpeg",
    phone: "0523456789",
    address: "الرياض، حي الورود",
  },
  {
    id: 5,
    product: "سماعات لاسلكية",
    price: 95,
    quantity: 1,
    total: 95,
    status: "مؤجل",
    date: "2023-08-22",
    customer: "نورة محمد",
    image: "../../images/product-5.jpeg",
    phone: "0534567890",
    address: "جدة، حي السلامة",
  },

  {
    id: 6,
    product: "تلفزيون ذكي",
    price: 1500,
    quantity: 1,
    total: 1500,
    status: "ملغي",
    date: "2023-08-21",
    customer: "خالد عبدالرحمن",
    image: "../../images/product-1.jpeg",
    phone: "0545678901",
    address: "الرياض، حي الملز",
  },
  {
    id: 7,
    product: "جهاز تابلت",
    price: 800,
    quantity: 1,
    total: 800,
    status: "ملغي",
    date: "2023-08-20",
    customer: "عبير أحمد",
    image: "../../images/product-2.jpeg",
    phone: "0556789012",
    address: "مكة، حي العزيزية",
  },

  {
    id: 8,
    product: "طابعة ليزر",
    price: 400,
    quantity: 1,
    total: 400,
    status: "مؤكد",
    date: "2023-08-19",
    customer: "سعود فيصل",
    image: "../../images/product-3.jpeg",
    phone: "0567890123",
    address: "جدة، حي الصفا",
  },
  {
    id: 9,
    product: "سماعات أذن",
    price: 120,
    quantity: 2,
    total: 240,
    status: "مؤكد",
    date: "2023-08-18",
    customer: "هند خالد",
    image: "../../images/product-4.jpeg",
    phone: "0578901234",
    address: "الرياض، حي الياسمين",
  },
  {
    id: 10,
    product: "ماوس لاسلكي",
    price: 75,
    quantity: 1,
    total: 75,
    status: "مؤكد",
    date: "2023-08-17",
    customer: "عمر سعد",
    image: "../../images/product-5.jpeg",
    phone: "0589012345",
    address: "الدمام، حي الفيصلية",
  },

  {
    id: 11,
    product: "شاحن متنقل",
    price: 85,
    quantity: 3,
    total: 255,
    status: "مشحون",
    date: "2023-08-16",
    customer: "ليلى عبدالله",
    image: "../../images/product-1.jpeg",
    phone: "0590123456",
    address: "الرياض، حي الربيع",
  },
  {
    id: 12,
    product: "كاميرا رقمية",
    price: 750,
    quantity: 1,
    total: 750,
    status: "مشحون",
    date: "2023-08-15",
    customer: "فيصل عبدالعزيز",
    image: "../../images/product-2.jpeg",
    phone: "0501234567",
    address: "جدة، حي المروة",
  },

  {
    id: 13,
    product: "جهاز سماعات منزلية",
    price: 350,
    quantity: 1,
    total: 350,
    status: "مستلم",
    date: "2023-08-14",
    customer: "سلمى علي",
    image: "../../images/product-3.jpeg",
    phone: "0512345678",
    address: "الرياض، حي الخليج",
  },
  {
    id: 14,
    product: "لوحة مفاتيح لاسلكية",
    price: 120,
    quantity: 1,
    total: 120,
    status: "مستلم",
    date: "2023-08-13",
    customer: "فهد ناصر",
    image: "../../images/product-4.jpeg",
    phone: "0523456789",
    address: "مكة، حي النسيم",
  },

  {
    id: 15,
    product: "سماعات رأس",
    price: 220,
    quantity: 1,
    total: 220,
    status: "مرتجع",
    date: "2023-08-12",
    customer: "نوف سعد",
    image: "../../images/product-5.jpeg",
    phone: "0534567890",
    address: "الرياض، حي العليا",
  },
  {
    id: 16,
    product: "شاشة كمبيوتر",
    price: 650,
    quantity: 1,
    total: 650,
    status: "مرتجع",
    date: "2023-08-11",
    customer: "طلال محمد",
    image: "../../images/product-1.jpeg",
    phone: "0545678901",
    address: "جدة، حي البوادي",
  },
];
