// Products data model for the inventory management system
export const products = [
  {
    id: 1,
    name: "كرسي مكتبي فاخر",
    sku: "CHAIR-001",
    category: "أثاث مكتبي",
    price: 450,
    costPrice: 250,
    stockQuantity: 15,
    minStockLevel: 5,
    imageUrl: "images/product-1.jpeg",
    description:
      "كرسي مكتبي مريح بتصميم عصري وإرجونومي، مناسب للاستخدام الطويل",
    lastRestockDate: "2023-08-10",
    supplier: "شركة الأثاث العالمية",
  },
  {
    id: 2,
    name: "طاولة مكتبية خشبية",
    sku: "DESK-002",
    category: "أثاث مكتبي",
    price: 1200,
    costPrice: 750,
    stockQuantity: 8,
    minStockLevel: 3,
    imageUrl: "images/product-2.jpeg",
    description: "طاولة مكتبية من خشب الزان الفاخر، بتصميم أنيق ومساحة واسعة",
    lastRestockDate: "2023-07-25",
    supplier: "شركة الأثاث العالمية",
  },
  {
    id: 3,
    name: "لابتوب احترافي",
    sku: "TECH-003",
    category: "إلكترونيات",
    price: 3200,
    costPrice: 2400,
    stockQuantity: 5,
    minStockLevel: 2,
    imageUrl: "images/product-3.jpeg",
    description:
      "لابتوب بمواصفات عالية للاستخدام الاحترافي، معالج قوي وشاشة عالية الدقة",
    lastRestockDate: "2023-08-15",
    supplier: "شركة التقنية الحديثة",
  },
  {
    id: 4,
    name: "شاشة كمبيوتر 27 بوصة",
    sku: "TECH-004",
    category: "إلكترونيات",
    price: 850,
    costPrice: 550,
    stockQuantity: 12,
    minStockLevel: 4,
    imageUrl: "images/product-4.jpeg",
    description: "شاشة كمبيوتر بدقة عالية، مناسبة للأعمال المكتبية والتصميم",
    lastRestockDate: "2023-08-05",
    supplier: "شركة التقنية الحديثة",
  },
  {
    id: 5,
    name: "هاتف ذكي",
    sku: "TECH-005",
    category: "إلكترونيات",
    price: 1500,
    costPrice: 1100,
    stockQuantity: 20,
    minStockLevel: 7,
    imageUrl: "images/product-5.jpeg",
    description: "هاتف ذكي بمواصفات عالية، كاميرا ممتازة وأداء سريع",
    lastRestockDate: "2023-08-12",
    supplier: "شركة التقنية الحديثة",
  },
  {
    id: 6,
    name: "طابعة ليزر ملونة",
    sku: "TECH-006",
    category: "إلكترونيات",
    price: 700,
    costPrice: 450,
    stockQuantity: 3,
    minStockLevel: 2,
    imageUrl: "images/product-1.jpeg",
    description: "طابعة ليزر ملونة، سريعة وذات جودة طباعة عالية",
    lastRestockDate: "2023-07-30",
    supplier: "شركة التقنية الحديثة",
  },
  {
    id: 7,
    name: "خزانة ملفات",
    sku: "FURN-007",
    category: "أثاث مكتبي",
    price: 600,
    costPrice: 350,
    stockQuantity: 7,
    minStockLevel: 3,
    imageUrl: "images/product-2.jpeg",
    description: "خزانة ملفات معدنية بتصميم أنيق، متينة ومقاومة للصدأ",
    lastRestockDate: "2023-07-20",
    supplier: "شركة الأثاث العالمية",
  },
  {
    id: 8,
    name: "قرطاسية مكتبية متكاملة",
    sku: "STAT-008",
    category: "قرطاسية",
    price: 120,
    costPrice: 65,
    stockQuantity: 25,
    minStockLevel: 10,
    imageUrl: "images/product-3.jpeg",
    description:
      "مجموعة متكاملة من القرطاسية المكتبية، تشمل أقلام ودفاتر وأدوات متنوعة",
    lastRestockDate: "2023-08-08",
    supplier: "شركة القرطاسية الأولى",
  },
  {
    id: 9,
    name: "آلة حاسبة متقدمة",
    sku: "STAT-009",
    category: "قرطاسية",
    price: 85,
    costPrice: 45,
    stockQuantity: 18,
    minStockLevel: 6,
    imageUrl: "images/product-4.jpeg",
    description: "آلة حاسبة متقدمة للاستخدام المالي والمحاسبي، بوظائف متعددة",
    lastRestockDate: "2023-08-01",
    supplier: "شركة القرطاسية الأولى",
  },
  {
    id: 10,
    name: "سماعات رأس لاسلكية",
    sku: "TECH-010",
    category: "إلكترونيات",
    price: 320,
    costPrice: 180,
    stockQuantity: 10,
    minStockLevel: 4,
    imageUrl: "images/product-5.jpeg",
    description: "سماعات رأس لاسلكية بجودة صوت عالية، مناسبة للعمل والترفيه",
    lastRestockDate: "2023-08-18",
    supplier: "شركة التقنية الحديثة",
  },
];

// Categories for filtering products
export const productCategories = [
  "أثاث مكتبي",
  "إلكترونيات",
  "قرطاسية",
  "مستلزمات مكتبية",
  "أخرى",
];

// Suppliers list
export const suppliers = [
  "شركة الأثاث العالمية",
  "شركة التقنية الحديثة",
  "شركة القرطاسية الأولى",
  "المورد المتكامل للمكاتب",
  "شركة التجهيزات المكتبية",
];

// Stock movements history for tracking inventory changes
export const stockMovements = [
  {
    id: 1,
    productId: 1,
    type: "إضافة", // إضافة، سحب، تعديل
    quantity: 10,
    date: "2023-08-10T09:30:00Z",
    notes: "استلام شحنة جديدة",
    userId: 4, // accountant ID
    previousStock: 5,
    newStock: 15,
  },
  {
    id: 2,
    productId: 2,
    type: "إضافة",
    quantity: 5,
    date: "2023-07-25T11:45:00Z",
    notes: "استلام شحنة جديدة",
    userId: 4,
    previousStock: 3,
    newStock: 8,
  },
  {
    id: 3,
    productId: 3,
    type: "سحب",
    quantity: 2,
    date: "2023-08-20T14:15:00Z",
    notes: "تحضير طلب #8",
    userId: 2, // stock manager ID
    previousStock: 7,
    newStock: 5,
  },
  {
    id: 4,
    productId: 4,
    type: "تعديل",
    quantity: 1,
    date: "2023-08-22T10:00:00Z",
    notes: "تسوية المخزون بعد الجرد",
    userId: 4,
    previousStock: 11,
    newStock: 12,
  },
  {
    id: 5,
    productId: 6,
    type: "سحب",
    quantity: 1,
    date: "2023-08-23T13:20:00Z",
    notes: "تحضير طلب #10",
    userId: 2,
    previousStock: 4,
    newStock: 3,
  },
  {
    id: 6,
    productId: 5,
    type: "إضافة",
    quantity: 8,
    date: "2023-08-12T09:00:00Z",
    notes: "استلام شحنة جديدة",
    userId: 4,
    previousStock: 12,
    newStock: 20,
  },
];

// Purchase orders for restocking
export const purchaseOrders = [
  {
    id: 1,
    supplier: "شركة الأثاث العالمية",
    orderDate: "2023-08-05T10:00:00Z",
    status: "مكتمل", // قيد الانتظار، مؤكد، مكتمل، ملغي
    items: [
      { productId: 1, quantity: 10, unitPrice: 250 },
      { productId: 2, quantity: 5, unitPrice: 750 },
    ],
    totalCost: 6250,
    receivedDate: "2023-08-10T09:30:00Z",
    notes: "تم استلام البضاعة بالكامل",
  },
  {
    id: 2,
    supplier: "شركة التقنية الحديثة",
    orderDate: "2023-08-10T14:30:00Z",
    status: "مكتمل",
    items: [
      { productId: 3, quantity: 3, unitPrice: 2400 },
      { productId: 5, quantity: 8, unitPrice: 1100 },
    ],
    totalCost: 15900,
    receivedDate: "2023-08-15T11:00:00Z",
    notes: "تم استلام البضاعة بالكامل",
  },
  {
    id: 3,
    supplier: "شركة القرطاسية الأولى",
    orderDate: "2023-09-01T09:15:00Z",
    status: "قيد الانتظار",
    items: [
      { productId: 8, quantity: 15, unitPrice: 65 },
      { productId: 9, quantity: 10, unitPrice: 45 },
    ],
    totalCost: 1425,
    receivedDate: null,
    notes: "بانتظار التأكيد من المورد",
  },
];
